(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c t") 'klairm/org-add-task)
(global-set-key (kbd "C-c i") 'imenu-list-smart-toggle)
(global-set-key (kbd "C-c n") 'elfeed)
